### ISSUE TITLE
Issues moved to Gitlab

### ISSUE THREAD

**Issue by feeefeee** [ubisoft/mixer#14]
Please post your issues at https://gitlab.com/ubisoft-animation-studio/mixer/-/issues instead of here.

Our internal development uses Gitlab, and in order to have all discussion threads in the same place, we prefer that the issues are posted to Gitlab.

Thanks for your cooperation.

**Comment by fire** [comment]
Can you copy and paste the issues and then make sure that the issues feature is disabled?

**Comment by fire** [comment]
@feeefeee Can you reopen #5
