### ISSUE TITLE
Crashes When Joining Room on 2.93.1

### ISSUE THREAD

**Issue by timm052** [ubisoft/mixer#20]
Having issues with crashing when people join rooms using 2.93.1 as host and client occurs across multiple hosts and only the client crashes. Tested on 2.92 and it has no issues connecting.

**Comment by FrederikPeik** [comment]
I've got exactly the same problem!

**Comment by MasterBananeman** [comment]
From what I can see in the docs at the moment, they say "The currently supported Blender version is 2.92.0".

**Comment by werwack** [comment]
Hello
I'll do the support for 2.93 next week ;)
I come back to you asap.

**Comment by FROMCITRUS** [comment]
If it helps, here's the crash log I get when the Blender instance crashes trying to connect to the host.
https://pastebin.com/H0rCSY9h
