### ISSUE TITLE
Blender 2.93.5 crashes when joining a room

### ISSUE THREAD

**Issue by ItzYPboi** [ubisoft/mixer#28]
**Infos on the context**
My device:
- Add-on version: 1.0.1
- Blender version: 2.93.5
- OS: Windows 10

My friend's device:
- Add-on version: 1.0.1
- Blender version: 2.93.5
- OS: Windows 11

**Describe the bug**
My friend can connect successfully to the session but his Blender crashes when trying to join a room.

**To Reproduce**
1. Use Hamichi to setup a VPN.
2. Have your pc be the localhost.
3. Your friend uses your Hamichi IPv4 to connect to the session.
4. He tries to join a room and instantly crashes.

**Expected behavior**
Blender doesn't crash and he can join the room successfully.

**Screenshots**
None.

**Additional context**
It might be because his OS is different but I highly doubt it.

**Comment by fire** [comment]
Please see if https://github.com/ubisoft/mixer/pull/27 fixes this.

**Comment by charlesfleche** [comment]
Thanks to @fire PR #27 this bug should be fixed in the `master` branch now. I'm going to close this bug for now, please reopen if you still experience issues.

**Comment by ItzYPboi** [comment]
Alright, thanks. I will let you guys know if it fixes it.

**Comment by ItzYPboi** [comment]
Yep, that fixed it, thanks
