### ISSUE TITLE
Unable to create server on Windows 7

### ISSUE THREAD

**Issue by samvila** [ubisoft/mixer#3]
When using the Blender addon version 0.14.0 on Windows 7 and by having the configuration set as localhost and the default port 12800, after clicking on the 'connect' button Blender freezes for a few seconds and then outputs this error:

Connecting to "localhost:12800" ...
unknown error

Blender version 2.83 official

**Comment by feeefeee** [comment]
Thank you for trying Mixer. Our development is focused on Windows 10 and we cannot investigate and solve this problem without your help.

There could be a platform dependant problem while launching the server process or while the server accesses the network resources. Here a few independant things you can try to investigate the problem:
- start Blender as administrator and then click `connect`
- under the `connect` button, open `Advanced options` the select `Log Level` = `DEBUG`, then click `Connect`. Check if you have any extra messages in the log.
- start the server process from the comand line:
  - change directory into the addon folder that contains the `mixer` folder
  - execute  `python.exe -m mixer.broadcaster.apps.server --log-level DEBUG`, ensuring that you use the python provided with Blender and ckeck the log. It there are no errors, then try to `Connect` from the mixer panel

**Comment by samvila** [comment]
Hi,

Thanks for the suggestions, this is what I tried:

- Starting Blender with admin didn't fix the issue
- The Log Level DEBUG didn't provide any other additional information, it's just displaying a generic 'Unknown error'
- Starting the server from the command line TOTALLY worked! after typing that command I was finally able to use the connect button on the interface. I think this is a very obscure solution for a user, it would be great it the addon could do this for the user automatically. I wouldn't be able to figure out the problem if it wasn't for your help. Hope you could improve this, also it would be highly beneficial if the log would provide more information rather than 'unknown error'.

All this said, I tried your addon and it looks amazing! I think you will keep improving it in certain areas that are missing, for example I cannot see the modifier applied from one user to another.

Thank you very much for sharing this with the Blender community!,

Sam

**Comment by Celeborn2BeAlive** [comment]
> Starting the server from the command line TOTALLY worked! after typing that command I was finally able to use the connect button on the interface. I think this is a very obscure solution for a user, it would be great it the addon could do this for the user automatically. I wouldn't be able to figure out the problem if it wasn't for your help. Hope you could improve this, also it would be highly beneficial if the log would provide more information rather than 'unknown error'.

Well the fact is, this is what the addon is trying to do under the hood when you click "connect" without having a server already launched. No clue why it does not work on Windows 7, we never had any problem with that on Windows 10 :/

As @feeefeee said we focus on Win10 only right now. If we find time for it we may try to debug this on a virtual machine running Win7.

**Comment by feeefeee** [comment]
Nice to read that you could start it, although it is clearly only a workaround.

If you are willing to make a bit of debugging, you can try to figure out if Mixer actually starts a `python.exe` process for the server, then have a look into `mixer/connection.py` :
- if the process was started, maybe the hardcoded connection timeout in [wait_for_server()](https://github.com/ubisoft/mixer/blob/387b19d4c2e65a6ed85bafbc7cb453ef283b2eee/mixer/connection.py#L88)  if not enough for your case and you can increase the number of attempts
- if the process was not started, there may be in [start_local_server()](https://github.com/ubisoft/mixer/blob/387b19d4c2e65a6ed85bafbc7cb453ef283b2eee/mixer/connection.py#L97) an issue related to `subprocess.Popen()` but I would expect `Popen` to `raise` in that case

**Comment by samvila** [comment]
> Nice to read that you could start it, although it is clearly only a workaround.
> 
> If you are willing to make a bit of debugging, you can try to figure out if Mixer actually starts a `python.exe` process for the server, then have a look into `mixer/connection.py` :
> 
> * if the process was started, maybe the hardcoded connection timeout in [wait_for_server()](https://github.com/ubisoft/mixer/blob/387b19d4c2e65a6ed85bafbc7cb453ef283b2eee/mixer/connection.py#L88)  if not enough for your case and you can increase the number of attempts
> * if the process was not started, there may be in [start_local_server()](https://github.com/ubisoft/mixer/blob/387b19d4c2e65a6ed85bafbc7cb453ef283b2eee/mixer/connection.py#L97) an issue related to `subprocess.Popen()` but I would expect `Popen` to `raise` in that case

Hi,

I will spend sometime trying to figure out the problem and I will share my progress with you as I progress along. I can keep doing tests for you if you want.

At the moment I'm having a little bit of problem to follow up your instructions. When you say about 'python.exe' process, do you mean open up the Windows Task Manager and check if 'python.exe' is being executed once I press the connect button on the addon? If that's the case it doesn't seem that it's launching 'python.exe'. 

With the latest update now I get a little bit more information in the console:

2020-08-07 02:43:39,153 E mixer.connection - Unable to start local server [.\mixer\connection.py:133]

**Comment by feeefeee** [comment]
> When you say about 'python.exe' process, do you mean open up the Windows Task Manager and check if 'python.exe' is being executed once I press the connect button on the addon?

This is exactly what I meant.

> If that's the case it doesn't seem that it's launching 'python.exe'.

There is problably an issue [around here](https://github.com/ubisoft/mixer/blob/2a6696ace69299e5d9f41ed2aeffecf50bda31f4/mixer/connection.py#L10) which I cannot debug without a Windows 7 at hand. This part of the code needs more error checking.

**Comment by Celeborn2BeAlive** [comment]
Closing this issue because we are moving discussions to https://gitlab.com/ubisoft-animation-studio/mixer.

@samvila If you want want to continue this discussion, please open a new issue on Gitlab, thanks !
