### ISSUE TITLE
Blender 2.93.5 crashes with Mixer 1.1.0-alpha2

### ISSUE THREAD

**Issue by rennmaus-coder** [ubisoft/mixer#31]
**Infos on the context**
- Add-on version: 1.1.0-alpha2
- Blender version: 2.93.5
- OS: Windows 11
- Settings: Default

**The bug**
I start two instances of blender, one for the room host, the other to connect to the room. (IP-Adress: localhost) When I try to enter the created room with my second instance of blender (IP-adress: localhost), my second instance crashes instantly.

**To Reproduce**
1. Go to Mixer, set IP-Adress to localhost
2. Click on connect
3. Create new room
5. Join room with second instance (localhost)
6. See Error

**Expected behavior**
No crash :)

**Screenshots**
None

**Additional Files**
Second instance console log: https://pastebin.com/McsWYaw2
Host instance console log: https://pastebin.com/tVULqrD2
Crash log: https://pastebin.com/DNkmg1QZ

(I am sorry, my computer language is set to german, so some parts of the stacktrace/Error may be in german. If there are any question, please feel free to ask me :))

**Comment by charlesfleche** [comment]
That should be fixed if the `master` branch. No release has been done yet, hopefully there will one soon.

**Comment by rennmaus-coder** [comment]
Works, thankssssss :) 👍
