### ISSUE TITLE
Blender 2.93.6 Crash

### ISSUE THREAD

**Issue by Allstreamer** [ubisoft/mixer#33]
**Infos on the context**
- Add-on version: 1.0.1 (2021-04-30)
- Blender version: 2.93.6
- OS: Windows 10 x64

**Describe the bug**
On connecting to a room Blender Instantly crashes on the site of the connecting person

**To Reproduce**
1. Create a room using mixer v1.0.1
2. Join the room
3. See error

**Expected behavior**
The connecting user should sync with the room.

**Additional context**
Originally was running over ngrok but i ruled out ngrok after testing with a local instance starting two blender instances on my local machine and running them on localhost, but the client still crashed.

**Comment by charlesfleche** [comment]
This bug should already be fixed in the `master` branch, but no release has been made yet.
