### ISSUE TITLE
Cannot Connect (Missing Attribute)

### ISSUE THREAD

**Issue by PrinceWizardWolf** [ubisoft/mixer#39]
I was trying to set up mixer on two computers (I have set up add ons before). However when I connect, on both computers it said "mixer.connect error : AttributeError("'by.app' object has no attribute 'binary_path_python'")"

The tutorial said a firewall might come up to allow acess, however nothing showed up on either computer. I tried running as admin, but had the same result.

Both computers are windows 10, blender 3.0
I also tried using older versions of blender, and mixer.

**Comment by sce285** [comment]
Same thing happened to me with the same specs.

**Comment by SourcePyX** [comment]
I'm having the same issue. I tried looking up fixes and saw that I need to change something in enviroment.py. But can't find that file.

No clue what to do now 😔

**Comment by AfroSpartan** [comment]
This is fixed by the following changes to **connection.py** in #37 
https://github.com/ubisoft/mixer/pull/37/files#diff-94ad601fd1504c9cb62d78aac31a2b64a521881f63582468fbb75f490ec6af82

Until it's merged you can easily add the 2 lines of changes yourself or just download and replace the file

**Comment by PrinceWizardWolf** [comment]
> This is fixed by the following changes to **connection.py** in #37 https://github.com/ubisoft/mixer/pull/37/files#diff-94ad601fd1504c9cb62d78aac31a2b64a521881f63582468fbb75f490ec6af82
> 
> Until it's merged you can easily add the 2 lines of changes yourself or just download and replace the file

Thank you!

**Comment by PrinceWizardWolf** [comment]
> This is fixed by the following changes to **connection.py** in #37 https://github.com/ubisoft/mixer/pull/37/files#diff-94ad601fd1504c9cb62d78aac31a2b64a521881f63582468fbb75f490ec6af82
> 
> Until it's merged you can easily add the 2 lines of changes yourself or just download and replace the file

Sorry, this didn't actually work, I got the same results.

**Comment by AfroSpartan** [comment]
> > This is fixed by the following changes to **connection.py** in #37 https://github.com/ubisoft/mixer/pull/37/files#diff-94ad601fd1504c9cb62d78aac31a2b64a521881f63582468fbb75f490ec6af82
> > Until it's merged you can easily add the 2 lines of changes yourself or just download and replace the file
> 
> Sorry, this didn't actually work, I got the same results.

Did you add the 2 lines manually or download and replace this file https://github.com/fire/mixer/blob/blender-3/mixer/connection.py?

**Comment by PrinceWizardWolf** [comment]
> 

I added the lines manually. I could try again?

**Comment by PrinceWizardWolf** [comment]
> > > This is fixed by the following changes to **connection.py** in #37 https://github.com/ubisoft/mixer/pull/37/files#diff-94ad601fd1504c9cb62d78aac31a2b64a521881f63582468fbb75f490ec6af82
> > > Until it's merged you can easily add the 2 lines of changes yourself or just download and replace the file
> > 
> > 
> > Sorry, this didn't actually work, I got the same results.
> 
> Did you add the 2 lines manually or download and replace this file https://github.com/fire/mixer/blob/blender-3/mixer/connection.py?

OK, it's working on both computers now, but it isn't connecting? One is local host, and the other I searched up my ip address on the other, however it just gives an error when I connect.

**Comment by Pixel48** [comment]
It should by fixed by now with #50
