### ISSUE TITLE
Great tool - Enquire about Roadmap. 

### ISSUE THREAD

**Issue by mdjustin** [ubisoft/mixer#7]
Hey there, 
Absolutely love the tool so far. I can already see the huge potential within the use of it for many applications. 

Just enquiring about a roadmap or at least a plan for the next step in development. Couple things I noticed while playing around with a couple of friends. 
 - Modifiers don't mirror across users, this limits the potential for talking about problems with modifier debugging for larger assets. 
 - I know this might be a bit early, but are there any plans for image streaming, or a way to handle sharing of image textures quickly across users. 

Overall Super super impressed with what has been achived so far, And excited to see what comes next. :)

**Comment by feeefeee** [comment]
Thank you for your feedback.

At this point, we do not have a public roadmap, but everyone agrees that modifiers and textures are absolute requirements, so these features are on the top of the list.

Stay tuned !

**Comment by mdjustin** [comment]
Sounds great there here, Good to know that these things are being worked on next. 

I do have one request about editing, Playing around with it. I noticed if two people are in edit mode for the same object, the mesh will update with whoever left that mode last. 

Would there be a way to possible tell the other users, that User A is currently editing the object?
Not a huge problem, but for those who aren't activly communicating it could become a problem when just working on stuff and making quick edits to things.

**Comment by Celeborn2BeAlive** [comment]
Yes we plan to add the current mode (EDIT, SCULPT, ...) of the user next to its name on top of its selection, we'll see if that's enough to notify others. We may also add options to lock selection of objects already selected by another users.

**Comment by mdjustin** [comment]
Sounds good, Excited to try out more and help with any problems that arise. 👍

**Comment by feeefeee** [comment]
About modifiers, see https://github.com/ubisoft/mixer/issues/10#issuecomment-672230813 and post your feedback in #10 if you try it

**Comment by Celeborn2BeAlive** [comment]
Also for modifiers support preview, use this link https://gitlab.com/ubisoft-animation-studio/mixer/-/jobs/703226702/artifacts/download to download a zip archive that can be installed into Blender

**Comment by Celeborn2BeAlive** [comment]
Closing this issue because we are moving discussions to https://gitlab.com/ubisoft-animation-studio/mixer.

Modifiers support is currently implemented in branch https://gitlab.com/ubisoft-animation-studio/mixer/-/tree/205-object-modifiers-and-constraints and you can find development releases here https://gitlab.com/ubisoft-animation-studio/mixer/-/releases

@mdjustin If you want want to continue this discussion, please open a new issue on Gitlab, thanks !
